//Authentication
export const ADD_USER = 'ADD_USER';
export const LOG_OUT = 'LOG_OUT';
export const SAVE_TOKEN = 'SAVE_TOKEN';

//Loader
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const CHAT_LOADING = 'CHAT_LOADING';
export const TAKES_LOADING = 'TAKES_LOADING';

//App story
export const GET_USER_LISTS = 'GET_USER_LISTS';
export const GET_USER_GROUPS = 'GET_USER_GROUPS';
export const GET_PUBLIC_GROUPS = 'GET_PUBLIC_GROUPS';
export const GET_ALL_BETS = 'GET_ALL_BETS';
export const GET_MY_BETS = 'GET_MY_BETS';
export const LIKE_BET_UPDATE = 'LIKE_BET_UPDATE';
export const GET_PENDING_BETS = 'GET_PENDING_BETS';
export const CLEAN_PENDING_BETS = 'CLEAN_PENDING_BETS';
export const GET_SPORTS_BETS = 'GET_SPORTS_BETS';

export const GET_PUBLIC_STANDINGS = 'GET_PUBLIC_STANDINGS';
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_TAKES = 'GET_TAKES';
export const GET_NEW_TAKE = 'GET_NEW_TAKE';
export const UPDATE_NEW_TAKE_REPLY = 'UPDATE_NEW_TAKE_REPLY';
export const UPDATE_EXISTING_TAKE = 'UPDATE_EXISTING_TAKE';
export const GET_MESSAGE = 'GET_MESSAGE';
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const UPDATE_COVER_IMAGE = 'UPDATE_COVER_IMAGE';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_NUMBER = 'CHANGE_NUMBER';
export const CHANGE_BIO = 'CHANGE_BIO';
export const CHANGE_FAVORITE_TEAMS = 'CHANGE_FAVORITE_TEAMS';
export const UPDATE_FOLLOWERS_AND_FOLLOWINGS =
  'UPDATE_FOLLOWERS_AND_FOLLOWINGS';

//watch party
export const GET_ALL_WATCH_PARTY = 'GET_ALL_WATCH_PARTY';

export const GET_PUBLIC_WATCH_PARTY = 'GET_PUBLIC_WATCH_PARTY';
export const GET_PRIVATE_WATCH_PARTY = 'GET_PRIVATE_WATCH_PARTY';

export const GET_GOLFER_LISTING = 'GET_GOLFER_LISTING';
// Chat Rooms
export const GET_CHAT_ROOMS = 'GET_CHAT_ROOMS';

// contest Party
export const GET_CONTEXT_PARTY = 'GET_CONTEXT_PARTY';

export const GET_PICKEM_CONTEXT_PARTY = 'GET_PICKEM_CONTEXT_PARTY';
export const GET_SELECTED_CONTEST = 'GET_SELECTED_CONTEST';
export const GET_CONTEXT_ALL_QUESTION = 'GET_CONTEXT_ALL_QUESTION';

export const GET_USER_CONTEXT_QUESTION = 'GET_USER_CONTEXT_QUESTION';

export const GET_AWARDS = 'GET_AWARDS';

export const GET_CONTEST_LEADERBOARD = 'GET_CONTEST_LEADERBOARD';

export const GET_SPORTS_LIST = 'GET_SPORTS_LIST';

export const GET_PROMOTIONAL_ADS = 'GET_PROMOTIONAL_ADS';

export const GET_SPORTS_FEED = 'GET_SPORTS_FEED';

export const SCROLL_INDEX = 'SCROLL_INDEX';

export const HASHTAG_LIST = 'HASHTAG_LIST';

export const MENTIONED_USERS_LIST = 'MENTIONED_USERS_LIST';

export const HASHTAGED_TAKES_LIST = 'HASHTAGED_TAKES_LIST';
