import { StyleSheet, Platform } from "react-native";
import { WP, COLORS, FONTS } from "../../../../services";
export const styles = StyleSheet.create({
  scroll: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  leaderboardContainer: {
    width: "100%",
  },
  headingText: {
    fontWeight: Platform.OS === "ios" ? "bold" : null,
    fontSize: WP("6"),
    fontFamily: FONTS.appFont,
    textAlign: "center",
    marginBottom: WP("3"),
  },
  descriptionText: {
    fontWeight: Platform.OS === "ios" ? "bold" : null,
    fontSize: WP("4"),
    fontFamily: FONTS.appFont,
  },
  groupContainer: {
    display: "flex",
    height: "auto",
    width: "100%",
    // borderRadius:WP('5'),
    // borderWidth:WP('0.5'),
    // borderColor:COLORS.black,
    // padding:WP('5'),
    marginTop: WP("3"),
  },
  renderRow: {
    display: "flex",
    flexDirection: "row",
    marginBottom: WP("3"),
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  renderRowText: {
    display: "flex",
    flexDirection: "row",
    marginBottom: WP("3"),
    alignItems: "center",
  },
  id: {
    color: COLORS.black,
    fontSize: WP("5"),
    fontWeight: Platform.OS === "ios" ? "bold" : null,
    fontFamily: FONTS.appFont,
    width: WP("7"),
    marginLeft: WP("2"),
  },
  idOne: {
    color: COLORS.appColour,
    fontSize: WP("5"),
    fontWeight: Platform.OS === "ios" ? "bold" : null,
    fontFamily: FONTS.appFont,
    width: WP("7"),
    marginLeft: WP("2"),
  },
  idTwo: {
    color: "#00FF00",
    fontSize: WP("5"),
    fontWeight: Platform.OS === "ios" ? "bold" : null,
    fontFamily: FONTS.appFont,
    width: WP("7"),
    marginLeft: WP("2"),
  },
  idThree: {
    color: "#FFA500",
    fontSize: WP("5"),
    fontWeight: Platform.OS === "ios" ? "bold" : null,
    fontFamily: FONTS.appFont,
    width: WP("7"),
    marginLeft: WP("2"),
  },
  publicId: {
    color: COLORS.black,
    fontSize: WP("5"),
    fontWeight: Platform.OS === "ios" ? "bold" : null,
    fontFamily: FONTS.appFont,
  },
  imgStyles: {
    display: "flex",
    height: WP("10"),
    width: WP("10"),
    borderRadius: 100,
    overflow: "hidden",
    resizeMode: "contain",
    // backgroundColor:'red',
    marginLeft: WP("8"),
  },
  searchbarContainer:{
    width:'100%',
  },
  searchBar: {
    width: '100%',
    borderColor: COLORS.textFieldBorder,
    // borderRadius:10,
    // marginHorizontal:10,
    paddingVertical:8,
    paddingHorizontal:10,
    borderWidth: 1,
  },
  imageSt: {
    height: "100%",
    width: "100%",
  },
  container: {
    display: "flex",
    flexDirection: "row",
  },
  idContainer: {
    width: WP("13"),
  },
  winContainer: {
    width: WP("30"),
  },
  wins: {
    fontWeight: Platform.OS === "ios" ? "bold" : null,
    fontSize: WP("3"),
    marginLeft: WP("2"),
    fontFamily: FONTS.appFont,
    width: Platform.OS === "ios" ? WP("10") : WP("10"),
  },
  name: {
    fontWeight: Platform.OS === "ios" ? "bold" : null,
    fontSize: WP("3"),
    marginLeft: WP("2"),
    fontFamily: FONTS.appFont,
    width: Platform.OS === "ios" ? WP("20") : WP("25"),
  },
  lost: {
    fontWeight: Platform.OS === "ios" ? "bold" : null,
    fontSize: WP("3"),
    marginLeft: WP("2"),
    fontFamily: FONTS.appFont,
    width: Platform.OS === "ios" ? WP("8") : WP("10"),
  },
  bar: {
    fontWeight: Platform.OS === "ios" ? "bold" : null,
    fontSize: WP("3"),
    marginLeft: WP("2"),
    fontFamily: FONTS.appFont,
    width: WP("2"),
  },
  ratio: {
    fontWeight: Platform.OS === "ios" ? "bold" : null,
    fontSize: WP("3"),
    marginLeft: WP("18"),
    fontFamily: FONTS.appFont,

    // width: "100%",
  },
  ppImage: {},
  noParticipant: {
    alignSelf: "center",
  },
  btn: {
    width: WP("13"),
    marginLeft: WP("2"),
    height: WP("13"),
  },
  text: {
    fontSize: WP("3"),
  },
  chatStyle: {
    height: WP("10"),
    width: WP("15"),
    resizeMode: "contain",
    alignSelf: "flex-end",
  },
});
