// "name":require('../../../../assets/icons')

export const APPLICATION_IMAGES = {
  downArrow: require('../../../../assets/icons/down_arrow.png'),
  Black_logo: require('../../../../assets/icons/unlogo.png'),
  upArrow: require('../../../../assets/icons/up_arrow.png'),
  contestFinished: require('../../../../assets/icons/undefeated-contest-finished.png'),
  DD_Selected: require('../../../../assets/icons/dd_selected.png'),
  DD_Unselected: require('../../../../assets/icons/dd_unselected.png'),
  Information: require('../../../../assets/icons/Information.png'),
  headerLogo: require('../../../../assets/icons/headerLogo.png'),
  backArrow: require('../../../../assets/icons/backArrow.png'),
  settingsLogo: require('../../../../assets/icons/settingsIcon.png'),
  // profilePicPlaceHolder: require('../../../../assets/icons/profilePicPlaceHolder.png'),
  profilePicPlaceHolder:
    'https://undefeatedimages.s3.amazonaws.com/default_app_images/defaut_profile',
  chevron: require('../../../../assets/icons/chevron.png'),
  groupImage1: require('../../../../assets/icons/chevron.png'),
  groupImage2: require('../../../../assets/icons/chevron.png'),
  groupImage3: require('../../../../assets/icons/chevron.png'),
  addGroup: require('../../../../assets/icons/addGroup.png'),
  publicStandings: require('../../../../assets/icons/publicStanding.png'),
  options: require('../../../../assets/icons/options.png'),
  send: require('../../../../assets/icons/true.png'),
  true: require('../../../../assets/icons/Green_tick.png'),
  cancel: require('../../../../assets/icons/false.png'),
  empty: require('../../../../assets/icons/Orange_circle.png'),
  increment: require('../../../../assets/icons/increase.png'),
  decrease: require('../../../../assets/icons/decrease.png'),
  chatIcon: require('../../../../assets/icons/chat.png'),
  bellIcon: require('../../../../assets/icons/bell.png'),
  sendChetat: require('../../../../assets/icons/send.png'),
  instagram: require('../../../../assets/icons/instagram.png'),
  likedB: require('../../../../assets/icons/FilledLike.png'),
  unLikedBet: require('../../../../assets/icons/unFilledLike.png'),
  likeCount: require('../../../../assets/icons/showLikes.jpg'),
  VsIcon: require('../../../../assets/icons/VsIcon.png'),
  pendingBets: require('../../../../assets/icons/pendingBets.png'),
  placeBet: require('../../../../assets/icons/placeBet.png'),
  news: require('../../../../assets/icons/camera2.png'),
  sendChat: require('../../../../assets/icons/send.png'),
  sendImage: require('../../../../assets/icons/camera2.png'),
  disableImage: require('../../../../assets/icons/disbled_image.png'),
  smileImage: require('../../../../assets/icons/smile3.png'),
  keyboardIcon: require('../../../../assets/icons/keyboard-icon.png'),
  sendVideo: require('../../../../assets/icons/upload_video_icon.png'),
  rightArrow: require('../../../../assets/icons/rightArrow.png'),
  rightArrowIcon: require('../../../../assets/icons/rightArrowIcon.png'),
  close: require('../../../../assets/icons/close.png'),
  add: require('../../../../assets/icons/add.png'),
  closeBlue: require('../../../../assets/icons/close_icons.png'),
  closeBlue: require('../../../../assets/icons/closeIcon.png'),
  closeModal: require('../../../../assets/icons/closeModal.png'),
  quickbet: require('../../../../assets/icons/QLogo.png'),
  question: require('../../../../assets/icons/question.png'),
  leaderboard: require('../../../../assets/icons/leaderboard.png'),
  leaderboardIcon: require('../../../../assets/icons/leaderboardIcon.png'),
  pp: require('../../../../assets/icons/perfectprize.png'),
  home: require('../../../../assets/icons/home.png'),
  contestIcon: require('../../../../assets/icons/contest.png'),
  chat: require('../../../../assets/icons/chatIcon.png'),
  plus: require('../../../../assets/icons/plus.png'),
  // bluePlus: require('../../../../assets/icons/bluePlus.png'),
  pickemAws:
    'https://undefeatedimages.s3.amazonaws.com/prod/static/pickem-party-bg.png',
  contestAws:
    'https://undefeatedimages.s3.amazonaws.com/prod/static/contest-party-bg.png',
  huddleAws:
    'https://undefeatedimages.s3.amazonaws.com/prod/static/huddle-bg.png',
  ImagePicker: require('../../../../assets/icons/imagePicker.png'),
  ImagePicker_white: require('../../../../assets/icons/imagePicker_white.png'),
  emoji: require('../../../../assets/icons/emoji.png'),
  emoji_white: require('../../../../assets/icons/emoji_white.png'),
  deleteit: require('../../../../assets/icons/deleteit.jpg'),
  deleteIcon: require('../../../../assets/icons/delete.png'),
  like: require('../../../../assets/icons/like.png'),
  dislike: require('../../../../assets/icons/dislike.png'),
  share: require('../../../../assets/icons/share.png'),
  dislike_filled: require('../../../../assets/icons/dislike_filled.png'),
  chaticon2: require('../../../../assets/icons/chatIcon2.png'),
  post: require('../../../../assets/icons/post.png'),
  plus: require('../../../../assets/icons/plus.png'),
  attach: require('../../../../assets/icons/attach.png'),
  down: require('../../../../assets/icons/downArrow.png'),
  sendVideoWhiteIcon: require('../../../../assets/icons/upload_video_icon.png'),
  sendVideoCreateTakeIcon: require('../../../../assets/icons/uploadVideoWhite.png'),
  // uploadVideoWhite.png
  editIconWhite: 'https://www.iconsdb.com/icons/preview/white/edit-xxl.png',
  editIconBlack: 'https://www.iconsdb.com/icons/preview/black/edit-xxl.png',
  calendar: 'https://www.iconsdb.com/icons/preview/white/calendar-9-xxl.png',
  coverPicPlaceholder:
    'https://undefeatedimages.s3.amazonaws.com/default_app_images/default_cover',
  phone: 'https://www.iconsdb.com/icons/preview/white/phone-68-xxl.png',
  email: 'https://www.iconsdb.com/icons/preview/white/email-5-xxl.png',
};
