import {StyleSheet, Platform} from 'react-native';
import {WP, COLORS, FONTS} from '../../../services';
export const styles = StyleSheet.create({
  scroll: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  textheading: {
    marginLeft: 27,
    fontWeight: 'bold',
    fontSize: 16,
    // color: COLORS.appColour,
  },
  username: {
    marginRight: 70,
    fontWeight: 'bold',
    fontSize: 16,
    // color: COLORS.appColour,
  },
  Score: {
    marginLeft: 15,
    fontWeight: 'bold',
    fontSize: 16,
    // color: COLORS.appColour,
  },
  headertext: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    maxWidth: '100%',
    paddingRight: 22,
    marginTop: 10,
    // marginLeft: 200,
  },
  headingText: {
    // fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    textAlign: 'center',
    color: COLORS.appColour,
    fontSize: WP('6'),
    fontWeight: 'bold',
    paddingBottom: 15,
    fontFamily: FONTS.appFont,
  },
  descriptionText: {
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    fontSize: WP('4'),
    fontFamily: FONTS.appFont,
  },
  groupContainer: {
    display: 'flex',
    height: 'auto',
    // borderRadius:WP('5'),
    // borderWidth:WP('0.5'),
    // borderColor:COLORS.black,
    // padding:WP('5'),
    marginTop: WP('3'),
  },
  renderRow: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: WP('3'),
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  renderRowText: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: WP('3'),
    alignItems: 'center',
  },
  id: {
    color: COLORS.black,
    fontSize: WP('5'),
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    fontFamily: FONTS.appFont,
    width: WP('10'),
  },
  publicId: {
    color: COLORS.black,
    fontSize: WP('5'),
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    fontFamily: FONTS.appFont,
  },
  imgStyles: {
    display: 'flex',
    height: WP('10'),
    width: WP('10'),
    borderRadius: 100,
    overflow: 'hidden',
    resizeMode: 'contain',
    // backgroundColor:'red',
    marginLeft: WP('3'),
  },
  imageSt: {
    height: '100%',
    width: '100%',
  },
  container: {
    display: 'flex',
    flexDirection: 'row',
  },
  idContainer: {
    width: WP('13'),
  },
  winContainer: {
    width: WP('30'),
  },
  wins: {
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    fontSize: WP('3'),
    marginLeft: WP('2'),
    fontFamily: FONTS.appFont,
    width: Platform.OS === 'ios' ? WP('10') : WP('10'),
  },
  name: {
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    fontSize: WP('3'),
    marginLeft: WP('2'),
    fontFamily: FONTS.appFont,
    width: Platform.OS === 'ios' ? WP('20') : WP('25'),
  },
  lost: {
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    fontSize: WP('3'),
    marginLeft: WP('2'),
    fontFamily: FONTS.appFont,
    width: Platform.OS === 'ios' ? WP('8') : WP('10'),
  },
  bar: {
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    fontSize: WP('3'),
    marginLeft: WP('2'),
    fontFamily: FONTS.appFont,
    width: WP('2'),
  },
  ratio: {
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    fontSize: WP('3'),
    marginLeft: WP('2'),
    fontFamily: FONTS.appFont,
    width: Platform.OS === 'ios' ? WP('13') : WP('13'),
  },
  noParticipant: {
    alignSelf: 'center',
  },
  btn: {
    width: WP('13'),
    marginLeft: WP('2'),
    height: WP('13'),
  },
  text: {
    fontSize: WP('3'),
  },
  chatStyle: {
    height: WP('10'),
    width: WP('15'),
    resizeMode: 'contain',
    alignSelf: 'flex-end',
  },
  searchbarContainer: {
    width: '100%',
  },
  searchBar: {
    width: '94%',
    borderColor: COLORS.textFieldBorder,
    // borderRadius:10,
    marginHorizontal: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    marginTop: 10,
    marginBottom: 5,
  },
});
