export const APPLICATION_CONSTANTS = {
  welcomeTextTitle: /*'Textme.Bet'*/ 'Undefeated.Live',
  welcomeTextSubTitle: /*`or it didn't happen...`*/ `Watch.Answer.Win!`,
  welcome: 'Welcome',
  phoneNumberPlaceHolder: 'Your phone number',
  phoneBookText: 'From Your Contacts',
  noContacts: 'No contacts found!',
  delete: 'Delete',
  description: 'Describe your Bet... ',
  groupDesc: 'Describe your Group',
  groupTitle: 'Name Your Group',
  chatTitle: 'Chat Title',
  watchPartyTitle: 'Watch Party Title',
  newsTitle: 'Add News URL',
  firstMessage: 'First Message',
  startChat: 'Start Chat',
  newsChat: 'Start News Chat',
  welcomeMessage: 'Welcome Message',
  betTitle: 'Bet Title',
  publicText: 'Select from App ',
  contacts: 'Select Person From Contacts ',
  privateGroup: 'Private Group',
  privateGroupDescription:
    'Toggle switch to make group private ,by default its public.',
  privateText: 'Select Group',
  privateWatchParty: 'Private Contest Party',
  privateWatchPartyDescription:
    'Toggle switch to make contest party private ,by default its public.',

  chooseWage: 'Create Your Own Bet',
  QuickWage: 'Add Quick Bets',
  public: 'Public',
  send: 'Send',
  createGroup: 'Create Group',
  createWatchParty: 'Create',
  cancel: 'Cancel',
  quickBetText: 'Quick Bets',
  quickBetDescriptions:
    'Quick Bets are in-game pre-defined bets. It allows users to make quick bets while watching the game.',
  privateStandings: 'Standings for Artâ€™s Group',
  publicStandings: 'Leaderboard',
  groupInvitation: 'Invite Members',
  modalTitle: 'Choose a Wager',
  quickBetsTitle: 'Quick Bets',
  golferTitle: 'Golfers',
  popular: 'Popular',
  noWagesFound: 'No popular wages found!',
  watchPartyMembers: 'Watch Party Members',
  purposedBet: 'Purposed Bet',
  quickWager: 'Wager',
  pickedBet: 'Picked Bet',
  messages: 'Messages',
  chat: 'Chat',
  settings: 'Settings',
  followText: 'Follow on Instagram',
  logout: 'Logout',
  createWager: 'Create Your Own Bet',
  loginPlaceHolder: 'Enter phone number',
  passwordPlaceHolder: 'Enter Password',
  dontHaveAccount: 'Sign up for' + ' Undefeated.Live',
  forgotText: 'Please enter registered phone number',
  newName: 'Please enter new name',
  newEmail: 'Please enter new email',
  newPhone: 'Please enter new phone number',
  newNamePlaceHolder: 'Enter Your First Name',
  newEmailPlaceHolder: 'Enter email',
  ChangePassword: 'Please enter old password and new password',
  resetPassword: 'Please enter new password',
  oldPasswordPlaceHolder: 'Enter old password',
  newPasswordPlaceholder: 'Enter new password',
  confirmNewPassword: 'Enter confirm new password',
  failedSendingOtp: 'Unable to send otp , please try again',
  failedSignUp: 'Unable to signup',
  invalidCode: 'Invalid code provided.',
  imageNotPossible: 'Unable to open camera',
  noInternet: 'Please turn on your internet connection',
  fillAllFields: 'All fields and image is required',
  allFields: 'All fields required',
  enterValidEmail: 'Enter valid email',
  passwordNotMatch: 'Password and confirm password does not match',
  enterMobileNumber: 'Enter phone number',
  enterMobileNumberAndPassword: 'Enter phone number and password',
  passwordUpdated: 'Password updated, please login',
  groupRequirments: 'Please name your group!',
  selectParticipants: 'Add Participant',
  selectGroup: 'selectGroup',
  failedFetchingUserList: 'Failed fetching user list',
  userReported: 'User reported successfully',
  noUserFound: 'No users found',
  youcanAddFiveParticipants: 'You can add only five participants',
  atleasttwoParticipants: 'Atleast two participants must be added',
  atleastOneParticipants: 'One participant must be added',
  groupNotCreated: 'Unable to create group',
  contestCodeError: 'Unable to join contest code',
  participantsAdded: 'Participants added',
  betOnePerson: 'You can only bet one person',
  betOneGroupOnly: 'You can bet with only one group at a time',
  addTitleDescriptionAndSelectParticipant:
    'Title , description ,wager and participant is required or check wager must be less than 5000',
  QuickBetsError: 'Please select quick bet to be sent!',
  BetPlaced: 'Bet has been placed successfully',

  //watch party
  SportsGameList: 'Select a sport',
  watchPartyNotCreated: 'Unable to create Party',
  turnoffQuestion: 'Unable to turn off the question',
  pickemWatchPartyNotCreated: 'Unable to create Pickem Watch Party',
  questionAnswerTimeout: "Time out! You can't answer these questions anymore",
  watchPartyDisableEnable: 'Unable to change the contest party status',
  Basketball: 'Basketball',
  Football: 'Football',
  Golf: 'Golf',
  Tennis: 'Tennis',
  Soccer: 'Soccer',
  TableTennis: 'TableTennis',
  Cricket: 'Cricket',
  Hockey: 'Hockey',
  Baseball: 'Baseball',
  Volleyball: 'Volleyball',
  Rugby: 'Rugby',

  //contest watch party
  contextWatchPartyTitle: 'Contest Title',
  team_one: 'Team 1',
  team_two: 'Team 2',
  USER_ADMIN: 2,

  ADD_CONTEXT_QUESTION_ERROR: 'Failed',
  noQuestionFound: 'No Question found',
  acceptPrivacyPolicy: 'Please accept the Privacy Policy',
  // Chat Rooms
  privateChatRoom: 'Private Huddle',
  privateChatRoomDescription:
    'Toggle switch to make Huddle private ,by default its public.',

  chatRoomTitle: 'Huddle Title',
  chatRoomNotCreated: 'Unable to create Huddle',
  chatRoomCreated: 'Huddle has been created',
  MESSAGE_TYPE: {
    IMAGE_ONLY: 'IMAGE_ONLY',
    TEXT_ONLY: 'TEXT_ONLY',
    IMAGE_WITH_TEXT: 'IMAGE_WITH_TEXT',
  },
};

export const APPLICATION_IMAGE_CONSTANTS = {
  contestFinished: require('../../../assets/icons/undefeated-contest-finished.png'),
  basketballImg: require('../../../assets/icons/Basket-ball.png'),
  tennisImg: require('../../../assets/icons/Tennis-ball.png'),
  golfImg: require('../../../assets/icons/Golf-ball.png'),
  footballImg: require('../../../assets/icons/American-football.png'),
  soccerImg: require('../../../assets/icons/Soccer.png'),
  cricketImg: require('../../../assets/icons/Cricket.png'),
  hockeyImg: require('../../../assets/icons/Hockey.png'),
  baseballImg: require('../../../assets/icons/Baseball.png'),
  volleyballImg: require('../../../assets/icons/Volleyball.png'),
  tableTennisImg: require('../../../assets/icons/Table_tennis.png'),
  rugbyImg: require('../../../assets/icons/Rugby.png'),

  contestWatchPartyCoverImg: require('../../../assets/icons/contest_party_new.png'),

  pickemWatchPartyCoverImg: require('../../../assets/icons/pickemparty_new.jpg'),
  huddleWatchPartyCoverImg: require('../../../assets/icons/huddle_new.png'),

  // question : require("../../../assets/icons/question.png"),
  // leaderboard : require("../../../assets/icons/leaderboard.png")
};
