import {StyleSheet, Platform, Dimensions} from 'react-native';
import {WP, COLORS, FONTS} from '../../../services';
export const styles = StyleSheet.create({
  wrapper: {
    alignItems: 'center',
    width: Dimensions.get('window').width,
    padding: 0,
    height: Dimensions.get('window').height,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  section: {
    // width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    // borderBottomColor: COLORS.textFieldBorder,
    // borderBottomWidth: 0.5,
    // backgroundColor: COLORS.white,
    // marginBottom:20,
    // elevation: 3,
    // shadowOpacity: Platform.OS === 'ios' ? 1 : null,
  },
  myContest: {
    // paddingHorizontal: 10,
    alignItems: 'center',
    resizeMode: 'contain',
    width: WP('90'),
    paddingVertical: 0,
    borderColor: COLORS.borderColor,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    overflow: 'hidden',
  },
  slider: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  heading: {
    textAlign: 'center',
    color: COLORS.appColour,
    fontSize: WP('6'),
    fontWeight: '600',
    paddingBottom: 5,
    fontFamily: FONTS.appFont,
    // paddingTop:10,
  },
  promo: {
    textAlign: 'center',
    color: COLORS.appColour,
    fontSize: WP('7'),
    fontWeight: 'bold',
    paddingVertical: 10,
    fontFamily: FONTS.appFont,
  },
  subHeading: {
    textAlign: 'center',
    color: COLORS.black,
    fontSize: WP('4'),
    fontWeight: 'bold',
    paddingVertical: 10,
  },
  btnContainer: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.black,
    height: WP('12'),
    width: WP('90'),
    borderWidth: 2,
    borderRadius: WP('3'),
    alignItems: 'flex-start',
    marginTop: WP('4'),
  },
  textBtn: {
    color: COLORS.black,
    marginLeft: WP('3'),
  },
  btnContainerComplete: {
    display: 'flex',
    width: WP('28'),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginBottom: WP('3'),
  },
  disputedContainer: {
    display: 'flex',
    width: WP('28'),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginBottom: WP('3'),
    backgroundColor: COLORS.delete,
  },
  completedContainer: {
    display: 'flex',
    width: WP('28'),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginBottom: WP('3'),
    backgroundColor: COLORS.green,
  },
  pendingContainer: {
    display: 'flex',
    width: WP('28'),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginBottom: WP('3'),
    backgroundColor: COLORS.orange,
  },
  textBtnComplete: {
    fontSize: WP('3'),
  },
  showGroups: {
    color: COLORS.black,
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    fontSize: WP('5'),
    marginTop: WP('5'),
    fontFamily: FONTS.appFont,
  },
  createGroup: {
    color: COLORS.white,
    fontFamily: FONTS.appFont,
    fontSize: WP('4'),
    fontWeight: Platform.OS === 'ios' ? '500' : null,
  },
  createGroupSubTitle: {
    color: COLORS.white,
    fontFamily: FONTS.appFont,
    fontWeight: Platform.OS === 'ios' ? '500' : null,
  },
  showBets: {
    color: COLORS.black,
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    fontSize: WP('5'),
    marginTop: WP('5'),
    marginBottom: WP('5'),
    fontFamily: FONTS.appFont,
  },
  imageContainer: {
    display: 'flex',
    height: WP('20'),
    width: WP('20'),
    borderRadius: 100,
    position: 'absolute',
  },
  sliderImage: {
    height: WP('50'),
    width: WP('90'),
    overflow: 'hidden',
    resizeMode: 'contain',
  },
  chatContainer: {
    // height: WP('50'),
    // width: WP('100'),
    paddingLeft: 1,
    overflow: 'hidden',
    borderColor: COLORS.borderColor,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    overflow: 'hidden',
    width: WP('90'),
    marginBottom: 20,
  },
  image: {
    height: WP('20'),
    width: WP('20'),
    borderRadius: 100,
    overflow: 'hidden',

    // resizeMode:'contain'
  },
  arrowImage: {
    height: WP('8'),
    width: WP('8'),
    borderRadius: 100,
    overflow: 'hidden',
  },
  betContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: WP('3'),
    alignSelf: 'center',
    backgroundColor: 'white',
    borderRadius: WP('2'),
    elevation: 3,
    shadowOpacity: 0.4,
    width: WP('88'),
  },
  acceptContainer: {
    display: 'flex',
    height: WP('30'),
    width: WP('90'),
    backgroundColor: COLORS.appColour,
    padding: WP('5'),
    borderRadius: WP('2'),
  },
  deleteContainer: {
    display: 'flex',
    height: WP('40'),
    width: WP('25'),
    backgroundColor: COLORS.delete,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: WP('3'),
    borderBottomRightRadius: WP('3'),
  },
  deleteText: {
    color: COLORS.white,
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    fontSize: WP('4'),
    fontFamily: FONTS.appFont,
  },
  joinText: {
    color: COLORS.white,
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    fontSize: WP('3'),
    fontFamily: FONTS.appFont,
  },
  titleText: {
    // color:COLORS.white,
    // fontWeight:Platform.OS === 'ios'?'bold':null,
    fontSize: WP('4'),
    fontFamily: FONTS.appFont,
    width: WP('80'),
  },
  wagerText: {
    fontSize: WP('4'),
    fontFamily: FONTS.appFont,
    marginBottom: WP('3'),
    fontWeight: Platform.OS === 'ios' ? 'bold' : null,
    width: WP('60'),
  },
  scroll: {
    flexGrow: 1,
    paddingTop: 0,
    // paddingBottom: 40,
  },
  userGroupsImage: {
    display: 'flex',
  },
  addGroup: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: COLORS.appColour,
    marginTop: WP('10'),
    height: WP('14'),
    borderRadius: WP('2'),
    alignItems: 'center',
    paddingLeft: WP('3'),
    paddingRight: WP('3'),
    justifyContent: 'space-between',
  },
  groupContaier: {
    display: 'flex',
    alignItems: 'center',
    marginTop: WP('2'),
  },
  error: {
    marginRight: WP('3'),
  },
  profilePicContainer: {
    display: 'flex',
    height: WP('12'),
    width: WP('12'),
    backgroundColor: 'grey',
    borderRadius: 100,
    overflow: 'hidden',
  },
  likeContainer: {
    display: 'flex',
    height: WP('5'),
    width: WP('5'),
    borderRadius: 100,
    overflow: 'hidden',
    marginBottom: WP('3'),
  },
  containerText: {
    display: 'flex',
    // borderBottomWidth:2,
    // borderColor:COLORS.appColour,
    margin: WP('3'),
    // width:WP('90'),
    marginBottom: WP('3'),
  },
  profile: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  containerWager: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  notification: {
    display: 'flex',
    alignSelf: 'flex-end',
    height: WP('10'),
    width: WP('10'),
  },
  cupStyles: {
    fontSize: WP('5'),
  },
  group: {
    display: 'flex',
    // height:WP('30'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleGroup: {
    fontWeight: 'bold',
    marginTop: WP('3'),
    width: WP('25'),
    textAlign: 'center',
  },
  joinTextContainer: {
    position: 'absolute',
    bottom: 2,
    right: 0,
    height: WP('7'),
    width: WP('11'),
    backgroundColor: COLORS.appColour,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: WP('5'),
    elevation: 2,
    shadowOpacity: 0.5,
  },
  privacyPolicyContainer: {
    position: 'absolute',
    bottom: '5%',
    width: '100%',
  },
  privacyPolicy: {
    textAlign: 'center',
    fontWeight: 'bold',
    color: COLORS.appColour,
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    textDecorationColor: COLORS.appColour,
  },
  btnContainerLink: {
    backgroundColor: COLORS.appColour,
    borderColor: COLORS.appColour,
    height: WP('12'),
    width: WP('65'),
    borderWidth: 2,
    borderRadius: 100,
    marginVertical: WP('10'),
  },
  textBtnLink: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: WP('4'),
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    textDecorationColor: COLORS.lightGrey,
  },
});
